<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="InetBankingV1" duration-ms="40269" started-at="2020-05-21T08:55:25Z" finished-at="2020-05-21T08:56:05Z">
    <groups>
    </groups>
    <test name="Bankingapp test" duration-ms="40269" started-at="2020-05-21T08:55:25Z" finished-at="2020-05-21T08:56:05Z">
      <class name="com.inetbanking.Testcase.TC_AddCustomerTest_003">
        <test-method status="PASS" signature="SetUp(java.lang.String)[pri:0, instance:com.inetbanking.Testcase.TC_AddCustomerTest_003@6e8dacdf]" name="SetUp" is-config="true" duration-ms="14202" started-at="2020-05-21T08:55:25Z" finished-at="2020-05-21T08:55:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="FAIL" signature="addNewCustomer()[pri:0, instance:com.inetbanking.Testcase.TC_AddCustomerTest_003@6e8dacdf]" name="addNewCustomer" duration-ms="23568" started-at="2020-05-21T08:55:39Z" finished-at="2020-05-21T08:56:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.inetbanking.Testcase.TC_AddCustomerTest_003.addNewCustomer(TC_AddCustomerTest_003.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCustomer -->
        <test-method status="PASS" signature="Teardown()[pri:0, instance:com.inetbanking.Testcase.TC_AddCustomerTest_003@6e8dacdf]" name="Teardown" is-config="true" duration-ms="1430" started-at="2020-05-21T08:56:03Z" finished-at="2020-05-21T08:56:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
      </class> <!-- com.inetbanking.Testcase.TC_AddCustomerTest_003 -->
    </test> <!-- Bankingapp test -->
  </suite> <!-- InetBankingV1 -->
</testng-results>
